// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/40c60850ad6c8175a62d5ab48c4e016ea5b3dffe/react/react-addons-pure-render-mixin.d.ts
declare namespace __React {
    interface PureRenderMixin extends Mixin<any, any> {}

    namespace __Addons {
        export var PureRenderMixin: PureRenderMixin;
    }
}

declare module "react-addons-pure-render-mixin" {
    var PureRenderMixin: __React.PureRenderMixin;
    type PureRenderMixin = __React.PureRenderMixin;
    export = PureRenderMixin;
}
