import ReactElement = __React.ReactElement;
import * as React from 'react';
import {DetailTableRow,SubtotalTableRow} from "./TableRow";
import {SubtotalBy} from "../models/ColumnLike";
import {ColumnDef} from "../models/ColumnLike";
import {ColumnFormat} from "../models/ColumnLike";
import {Row} from "../models/Row";
import {TableRowColumnDef} from "../models/ColumnLike";
import {SubtotalRow} from "../models/Row";
import {DetailRow} from "../models/Row";
import {TableHeader} from "./TableHeader";
import {TreeRasterizer} from "../static/TreeRasterizer";
import {Tree} from "../static/TreeBuilder";
import {GigaGridStateStore} from "../store/GigaGridStateStore";
import * as Flux from 'flux';
import * as FluxUtils from 'flux/utils';
import ReduceStore = FluxUtils.ReduceStore;
import Dispatcher = Flux.Dispatcher;
import {GigaGridAction} from "../store/GigaGridStateStore";

export interface GigaGridProps extends React.Props<GigaGrid> {
    initialSubtotalBys?:SubtotalBy[];
    data:any[];
    columnDefs:ColumnDef[];
}

export interface GigaGridState {
    tree:Tree;
    subtotalBys:SubtotalBy[];
}

/**
 * The root component of this React library. assembles raw data into `Row` objects which are then translated into their
 * virtual DOM representation
 *
 * The bulk of the table state is stored in `tree`, which contains subtotal and detail rows
 * Rows can be hidden if filtered out or sorted among other things, subtotal rows can be collapsed etc
 * mutations to the state of table from user initiated actions can be thought of as mutates on the `tree`
 *
 * IMPORTANT: GigaGrid the component does not actually mutate its own state nor give its children the ability
 * to mutate its state. State mutation is managed entirely by the GigaGridStateStore flux-like Store. Events generated by the
 * children of this component are emitted to a central dispatcher (eventemitter3) and are dispatched to the GigaGridStateStore
 *
 * Please DO NOT pass a reference of this component to its children nor call setState() in the component
 */

export class GigaGrid extends React.Component<GigaGridProps, GigaGridState> {


    private store:GigaGridStateStore;
    private dispatcher:Dispatcher<GigaGridAction>;

    constructor(props:GigaGridProps) {
        super(props);
        this.dispatcher = new Dispatcher<GigaGridAction>();
        this.store = new GigaGridStateStore(this.dispatcher, props);
        this.state = this.store.getInitialState();
    }

    render() {
        // TODO first pass implementation ... need to make better, the final implementation will wrap things like scrollbar and footers
        const tableRowColumnDefs:TableRowColumnDef[] = this.props.columnDefs.map(cd => {
            return {
                colTag: cd.colTag,
                title: cd.title,
                aggregationMethod: cd.aggregationMethod,
                format: cd.format,
                width: "auto"
            };
        });

        return (
            <div className="giga-grid">
                <table>
                    {this.renderColumnHeaders(tableRowColumnDefs)}
                    <tbody>
                        {this.renderTableRows(tableRowColumnDefs)}
                    </tbody>
                </table>
                {this.renderTableFooter()}
            </div>);
    }

    renderColumnHeaders(tableRowColumnDefs:TableRowColumnDef[]):ReactElement<{}> {
        const ths = tableRowColumnDefs.map((colDef:TableRowColumnDef, i:number)=> {
            return <TableHeader tableColumnDef={colDef} key={i} isFirstColumn={i===0}
                                isLastColumn={i===tableRowColumnDefs.length-1}/>
        });
        return (
            <thead>
                <tr>{ths}</tr>
            </thead>
        );
    }

    renderTableRows(tableRowColumnDefs:TableRowColumnDef[]):ReactElement<{}>[] {
        // TODO consider whether this should be part of GigaGridStateStore somehow ... we don't want to always re-rasterize
        const rows:Row[] = TreeRasterizer.rasterize(this.state.tree);
        // convert plain ColumnDef to TableRowColumnDef which has additional properties
        return rows.map((row:Row, i:number)=> {
            if (row.isDetail())
                return <DetailTableRow key={i} tableRowColumnDefs={tableRowColumnDefs} row={row as DetailRow}/>;
            else
                return <SubtotalTableRow key={i} tableRowColumnDefs={tableRowColumnDefs} row={row as SubtotalRow}/>
        });
    }

    renderTableFooter() {
        // TODO dummy implemenation, replace with pagination
        return (<div></div>);
    }
}
